### ISSUE TITLE
Cant get vehicle spawns

### ISSUE THREAD

**Issue by chris0135** [Pwnoz0r/DayZ-Private-Server#139]
I have downloaded the 1.8.3, and there is an issue with the function pMain. It says cannot define @root@ or something like that. Everything works fine there is just no vehicles. In Navicat Object_data has nothing in it. I even tried bringing an old object data into navicat, but those vehicles do not transfer over. Thanks in advance

**Comment by Pl4nky** [comment]
Edit the pMain stored procedure and change this line:

CREATE DEFINER=`root`@`%` PROCEDURE `pMain`(IN `i` INT)

to

CREATE DEFINER=`dayz`@`localhost` PROCEDURE `pMain`(IN `i` INT)

Seems the root account in the SQL DB was removed or changed to dayz, but this stored proc wasn't updated.
