### ISSUE TITLE
Hive error: Error loading required resources... Help?

### ISSUE THREAD

**Issue by Sycho56** [Pwnoz0r/DayZ-Private-Server#141]
Recently I've been trying to host a private DayZ mod server for me and my friends to play on, and I've been having an issue that I can't find a work around for and was wanting some help. When I open the server up everything starts up fine, but when I try to join my server the mission for DayZ starts loading and the game tries receiving the data for it. At which point the HiveExt console opens and a little popup appeares that's labeled "Hive error" with the words "Error loading required resources." Also the HiveExt console it self has "HiveEXT<0>: [Information] HiveExt ce45a1f7524c." I have no clue what to do from here and would really like some assistance. Thank you very much in advance for your time.

**Comment by sgtpera** [comment]
I do not know if it will help, but I had some problems with hive and also do not remember very well what I did to solve, I changed folders with an old server and it worked, I think it was a hive or MySQL folder. This link ( https://drive.google.com/folderview?id=0B5OCScqIW-2QfnVOWEwzMGZpRWhRazNmcVByZVRyRVZqLV9BU0cxWHJfVzFFVFk3ckZQLVE&usp=sharing ) you can download my file servers to test, to play on lan with friends indicate the sarge_bandit folder, ARMA2OA and DAYZ_MOD game should be no beta updates in the steam version. I hope it works for you, have fun.
Excuse my English, I am Brazilian and I have not practiced much lately.
PS: Copy all files from folder "arma2OA" for a created folder (name choice), copy all the files from the folder "ARMA2" for this same newly created folder, merge and replace all the folders and files required, copy all Server folder of files downloaded to the same newly created folder, merge and replace all the folders and files required. Start the file @ START_SERVER.bat and wait for your server go online.

**Comment by sgtpera** [comment]
The link has been updated with compressed folders for easy downloading

https://drive.google.com/folderview?id=0B5OCScqIW-2QfnVOWEwzMGZpRWhRazNmcVByZVRyRVZqLV9BU0cxWHJfVzFFVFk3ckZQLVE&usp=sharing

**Comment by Sycho56** [comment]
Thank you so much for the reply, I will be sure to try that out the next time I get the chance. I really do appreciate your help :)
