### ISSUE TITLE
Server Start Batch file needs modification

### ISSUE THREAD

**Issue by abdros** [Pwnoz0r/DayZ-Private-Server#152]
The line that starts with:

`START .\Expansion\beta\arma2oaserver.exe -mod=Expansion\beta;Expansion\beta\expansion;ca;@hive;@dayz`

will not work. The location of the arma2oaserver.exe has changed. It should start with:

`START .\arma2oaserver.exe -mod=Expansion\beta;Expansion\beta\expansion;ca;@hive;@dayz`

Abdros

**Comment by jonrainier** [comment]
Updated and uploaded a few days ago, thanks for reporting.
